### PR TITLE
feat: Adding homepage

### PR DESCRIPTION
**Pull request by pkspyder007**

### CODE REVIEW

**Comment by shivam-tripathi** [comment]
@pkspyder007 Looks good to me. Let's update the contact us page and then we can merge this

**Comment by shivam-tripathi** [comment]
@pkspyder007 One of my concerns is about CSS files, would we be better off using CSS in JS solution like emotion, or css loaders in JS. Also, SASS vs CSS?

**Comment by pkspyder007** [comment]
Sass will be a better choice and as our site won't have many components we can also use styledcomponents.

**Comment by shivam-tripathi** [comment]
@pkspyder007 Any reason for closing this?

**Comment by pkspyder007** [comment]
@shivam-tripathi There were few bugs and i am revamping the styling using css in js technique. 
 Changing mdx format to md only for articles

**Comment by shivam-tripathi** [comment]
@pkspyder007 We might need some react component inside md files, for example maybe for footer or header. So mdx may make more sense in that case.

**Comment by pkspyder007** [comment]
Sure, we can add both md and mdx support. 
Will add this feature in next pr

**Pull request closed without merging**
